version: "3.9"
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: activitydash_development
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    command: go run server.go
    volumes:
      - .:/home/docker/app
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
